### GET users
POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "jose@gmail.com",
  "firstname": "Jose",
  "lastname1": "López",
  "lastname2": "López",
  "role": "O"
}

### GET users
GET http://localhost:8080/users
Accept: application/json

### GET one user
GET http://localhost:8080/users/miguel@gmail.com
Accept: application/json

### POST user
POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "jose@gmail.com",
  "firstname": "Jose Koala",
  "lastname1": "López",
  "lastname2": "Reyes",
  "role": "O"
}

### DELETE user
DELETE http://localhost:8080/users/jose@gmail.com
Accept: application/json